theme: jekyll-theme-slatetitle: "Ali A. Isse"
description: "Ph.D. student · International Relations · Coercion & Counterproliferation"
theme: minima   
  name: "Ali A. Isse"
  email: your.name@uni.edu
github_username: issemehdi
logo: /assets/headshot.jpg
